[package]
name = "hashcaster-lincheck"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
hashcaster-primitives = { workspace = true }

num-traits = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
